[msbuild]
project = "../aFRR-Service/aFRR-Service.sln"
[github]
user = "diversiwaver"
repo = "aFRR-NET"

[nuget]
publish = false
[changelog]
publish = false

[[pack]]
publish = false
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]

[[pack]]
publish = false
rid = ["rhel-x64"]
kinds = ["rpm", "tar"]

[[pack]]
publish = false
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]