name: CICD

on:
	push:
		branches: [ main ]
	workflow_dispatch:

jobs:
	Build:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3
			- name: Setup .NET
				uses: actions/setup-dotnet@v3
				with:
					dotnet-version: 6.0.x
			- name: Restore dependencies
				run: dotnet restore
			- name: Build
				run: dotnet build --no-restore
	DeployDev:
		runs-on: ubuntu-latest
		needs: [Build]
		name: Deploy to Dev 
		environment: 
			name: Development
		steps:
		- name: Deploy
			run: dotnet test --no-build --verbosity normal
	DeployProd:
		name: Deploy to Production 
		needs: [DeployDev]
		runs-on: ubuntu-latest
		environment: 
			name: Production
		steps:
			- name: Deploy
			run: echo Deploying to production...
			run: echo Deployed to production